### ISSUE TITLE
Ideas and plans for 2.0.0 roadmap

### ISSUE THREAD

**Issue by mrhyde** [LotusTM/Kotsu#177]
At the moment it's just a list of possible features and ideas for future release

## Global
- [ ] Refactor existing data pipeline and focus on unidirectional approach 
- [ ] Get rid of `grunt` as task runner
 
## Configuration
- [ ] `kotsu init` to bootstrap new project
- [ ] Transparent and flexible system to store projects configurations
- [ ] Ability to update Kotsu in existing projects with minimum effort

## Templates
- [ ] Replace nunjucks with something else (?)
- [ ] Move templates to React (?)

## i18n

**Comment by ArmorDarks** [comment]
I generally think that React or Vue is the way to go further.

I had for quite a long time idea about rendering static pages with React. This gives a lot of flexibility, since when you suddenly need to augment client pages with more dynamic features, you can always serve to client static page and then load same React app on frontend. It will kick-in, and magic will start to happen.

This sounds to me much more superior than usual server-side rendering approach + booting React on frontend, since on contrary to server-side rendering, already rendered static pages is as fast as you can go at all, while providing same functionality. After all, if half of content is static (promo pages, etc), there is no reason to serve them each time with additional server.

Turned out, I'm not the only one who thinks alike, and there are already some tools for it: https://www.youtube.com/watch?v=eTeO2CzV3Ys

**Comment by ArmorDarks** [comment]
With React or Vue, generally, I see only few downsides:

1. In terms of templating, their syntax isn't that expressive as Nunjucks. It is harder to gasp for novices.

   Though, it doesn't affect writing of templates. I almost never felt like writing on React harder than wih Nunjucks, even despite it is weaker in terms of expressivness and have some caveats.

   But newcommers or content editors will definitely suffer in comparison with mostly pure Nunjucks.

2. React doesn't have such powerful inheritance (extends) as Nunjucks does, and due to it's specific nature, it is almost impossible to replicate with React.

   However, I think it is possible to live with it, since on contrary React provides very powerful composition, which Nunjucks doesn't have. Usually this allows to achieve very similar effect, but doing it in other way. As a side benefit, React doesn't render templates "backwards", as Nunjucks and Jinja2 does, thus flow of data and redefinitions of properties are quite straightforward.

   For instance, in Nunjucks we would have something like:

   ```jinja
   {# /_layouts/_base.nj #}

   <html>

     <head>
       <title>Test</title>
     </head>

     <body class='o-panel o-panel--max'>
       {% block body %}{% endblock %}
     </body>

   </html>


   {# /index.nj #}

   {% extends '_layouts/_base.nj' %}

   {% block body %}
   <header class='Header h-margin-ends'>
     Content header
   </header>

   <main class='Main o-panel__body o-panel' role='main'>
     {% block main %}{% endblock %}
   </main>

   <footer>Footer</footer>
   {% endblock %}


   {# /index.nj #}

   {% extends '_layouts/_main.nj' %}

   {% block main %}
   <div>main content</div>
   {% endblock %}
   ```

   And in React it would be

   ```js
   // base layout is skipped, since React does not define <html>


   // /layouts/Main.js

   export default MainLayout = ({ children }) => (
     <div>

       <header class='Header h-margin-ends'>
         Content header
       </header>

       <main class='Main o-panel__body o-panel' role='main'>
         {children}
       </main>

       <footer>Footer</footer>

     </div>
   )

   // /Index.js

   import MainLayout from './layouts/Main.js'

   export default Index = () => (
     <MainLayout>
       <div>main content</div>
     </MainLayout>
   )
   ```

   It even looks very alike, but it isn't inheritance, but straightforward composition.

**Comment by ArmorDarks** [comment]
After giving it more thoughts, I think there is still one thing which might be worth to do before moving to something really radical.

I think we should think about swapping `grunt-nunjucks-2-html` for [metalsmith](http://www.metalsmith.io/).

It works in similar way as a Gulp and pipes your file through transform plugin (Nunjucks can be one of them). This sounds simple, but result in ability to generate very powerful chains. It doesn't solve all our problems, but, for instance, resolves #182 and allow to apply more transforms to our templates, and what is really important, those transforms will be very predictable and declared in single place.

What bothers me, though, is that Metalsmith is very close to Gulp, and, in fact, relatively same thing can be done with Gulp too. But my guess is that Metalsmith more adapted to work with templates.

As a hint for myself, __we should check how watch reloading will work with large set of files_. Because while in Grunt we can use `grunt-newer`, it won't be possible with pipelined process in Metalsmith.

**Comment by ArmorDarks** [comment]
However, I shouldn't fuel myself too... The issue with attempts to make changes only to "newer" files within pipeline is that some other files can rely on each other. For instance, another page might request Gray Matter data from another page, and since it will be updated only partially, it will result in artifacts. To tackle this issue with Grunt we anyway _recompile all Gray Matter data for all files even when you change 1 file_, so, we're manipulating upon all files anyway, there shouldn't be performance loss if that will be done within pipeline. After going through such dependants steps in pipeline, it is possible to exclude rendering of not updated files afterwards, by filtering.

Worth noting, that current Grunt system isn't ideal in this matter too. First of all, it takes a lot of time just to load `grayMatter` task before making a sweep. And second — if you will change one page's Matter data which loaded inside another page, that another page won't be updated until you will resave it manually. 

So yeah, it sounds to me like pretty much same drawbacks as with Grunt, but with ability to transform files more intensively and more freedom.

**Comment by ArmorDarks** [comment]
Yeap, this article justifies some my conerns in regards of Gulp vs Metalsmith: http://nathanblack.org/post/migration-to-static-site-via-gulp/

**Comment by ArmorDarks** [comment]
Some more related thoughts in this comment: http://stackoverflow.com/questions/23227248/is-there-some-gulp-plugin-that-lets-it-perform-the-function-of-a-static-site-gen/23858857?sgp=2#23858857

**Comment by ArmorDarks** [comment]
Just stumbled upon [taskr](https://github.com/lukeed), which is used in [next.js](https://github.com/zeit/next.js/).

It seems to be similar to Gulp, but with some interesting [concepts](https://github.com/lukeed/taskr/issues/3). Though, nothing extraordinary.

**Comment by ArmorDarks** [comment]
I'm replying https://github.com/LotusTM/Kotsu/issues/383#issuecomment-375967924 here because it's more relevant to this issue:

> Nimble future of JSPM and it's unstable state

It would be much easier to decide if we could know how far it's from promised JSPM 2, and what JSPM 2 would be.

It also depends on how we're going to use build tools. For instance, if we will use JSPM or Webpack in the scope of task runner like Gulp or mentioned Taskr, I do not see any issues at all, since it just a matter of swapping a tool, which is responsible only for frontend scripts. So, we can swap JSPM for Webpack or any other popular alternative for now, and return to it when JSPM 2 will emerge. Kotsu tied to JSPM right now, but very marginally. Mostly with hot reloading handling.

However, Webpack could be used as a complete replacement for any task runner, and that's where I'm really concerned...

> Replacement of grunt with more suitable and progressive alternative

Yeap, an old question. So far we have a Webpack, Gulp or Taskr. Webpack is the most questionable of all because its approach is totally different from typical task runners. I even concerned, would it be able to sustain good build times while watching large projects...

> First level support for SPA/PWA

I don't know what exactly we can improve here right now. Kotsu out of the box has almost everything you would need for basic SPA, including hot reloading. However, it requires some additions. Just to be clear, here they are:

1. Remove most part (but not all) Nunjucks templates, related tests.

   We are not removing Nunjucks completely because even SPA still need some basic templates to bootstrap `index.html`

2. Add to `index.nj` entry point (`<div id='#app></div>). It depends on view library.
3. Install additional dependencies, which also depends on view library.
4. Disable Grunt tasks, which aren't usable in SPA, like `uncss` or `grunt-sitemap-xml`
5. Add related to view JavaScript boilerplate. Once again, nothing we can do here since it depends on view library.

Other steps are typical for Kotsu init in general, like removing not needed predefined in Styles components, setting up languages and so on.

So, it would be cool to automate this, but so far I have no idea how. And hopefully, we will avoid maintaining a specific build of Kotsu just for specific libraries...

Some tools like yeoman can help here, but I do not want to make core Kotsu repository into a collection of templates for a generator.

Regarding PWA, yeap, we definitely need a service worker. I've created a standalone issue #384

**Comment by ArmorDarks** [comment]
https://twitter.com/jspm/status/961536568874979328
